config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :welcome
  resources :petitions
end

app/models/petition.rb
class Petition < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/petitions_controller.rb
class SunlightLabs::Congress::Legislator
  attr_accessor :skype_link
end

class PetitionsController < ApplicationController
  def index
    @petitions = Petition.all
  end

  def show
    @petition = Petition.where(id: params[:id]).first

    if params[:search] && params[:search][:zip]
      @zip = params[:search][:zip]
      @legislators = SunlightLabs::Congress::Legislator.where(zip: params[:search][:zip])

      if @legislators.empty?
        flash.alert = "No representatives found."
        redirect_to welcome_index_path
      else
        @legislators.each do |l|
          l.skype_link = 'skype:+1' + l['phone'].gsub(/[^\d]/, '') + '?call'
          if l.last_name == 'Gillibrand'
#            l.twitter_id = 'SenGillibrand'
          end
        end
      end
    end
  end
end

app/controllers/welcome_controller.rb
require File.join(Rails.root, 'lib/sunlight_manager.rb')

class WelcomeController < ApplicationController
  def index
    if params[:search] && params[:search][:zip]
      @zip = params[:search][:zip]
      @legislators = SunlightManager.new.get_by_zip(params[:search][:zip])

      if @legislators.empty?
        flash.alert = "No representatives found."
        redirect_to welcome_index_path
      else
        @legislators.each do |l|
          l['skype_link'] = 'skype:+1' + l['phone'].gsub(/[^\d]/, '') + '?call'
          if l['last_name'] == 'Gillibrand'
            l['twitter_id'] = 'SenGillibrand'
          end
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Petitioneer' %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext', media: 'all' %>
  <script type="text/javascript" async src="//platform.twitter.com/widgets.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/petitions/_form.html.erb
<%= form_for @petition do |f| %>
   <p>
      <%= f.label :petition_text %>
      <%= f.text_area :petition_text, cols: 100, rows: 10 %>
   </p>

   <p>
      <%= f.label :phone_script %>
      <%= f.text_area :phone_script, cols: 100, rows: 10 %>
   </p>

   <p>
      <%= f.label :tweet_text %>
      <%= f.text_area :tweet_text, cols: 75, rows: 2 %>
   </p>

   <p>
      <%= f.label :petitioner %><br>
      <%= f.text_field :petitioner, size: 80 %>
   </p>

<% end %>

app/views/petitions/_petition.html.erb
<tr>
   <td><%= petition.petitioner %></td>
   <td><%= petition.petition_text %></td>
   <td><%= petition.tweet_text %></td>
   <td><%= petition.phone_script %></td>
   <td><%= link_to('Tweetstorm!', petition) %></td>
</tr>

app/views/petitions/_petition_table.html.erb
<table>
   <tr>
      <th>Title</th>
      <th>Email Text</th>
      <th>Tweet Text</th>
      <th>Phone Script</th>
      <th>Hit 'Em Up</th>
   </tr>

   <%= render petitions %>
</table>

app/views/petitions/index.html.erb
<%= render partial: 'petition_table', locals: { petitions: @petitions} %>

app/views/petitions/show.html.erb
<% content_for :title do %>
   <%= "#{@petition.tweet_text}" %>
<% end %>

<div class='purple_info'>
   <%= render partial: 'petition_table', locals: { petitions: [@petition] } %>
</div>

<div class='basic_info'>
<%= form_tag(petition_path(@petition), method: :get, class: 'navbar-form', id: 'search-form') do %>
   <%= label_tag(:search_by_zip) %>
   <%= text_field(:search, :zip) %>
<% end %>
</div>

<% if @legislators %>
   <div class='basic_info'>
      <table>
         <tr>
            <th>Chamber</th>
            <th>Name</th>
            <th>Phone</th>
            <th>Skype</th>
            <th>Tweet</th>
            <th>Facebook</th>
            <th>Email</th>
            <th>Raw email</th>
            <th>Contact Form</th>
         </tr>

         <% @legislators.each do |l| %>
            <tr>
               <td><%= "#{l.chamber}" %></td>
               <td><%= "#{l.first_name} #{l.last_name}" %></td>
               <td><%= link_to("#{l.phone}", "tel:#{l.phone}") %></td>
               <td><%= link_to('skype their phone number', l.skype_link) %></td>
               <% if l.twitter_id %>
                  <td><%= link_to('tweet your support', "http://twitter.com/intent/tweet?text=#{@petition.tweet_text} @#{l.twitter_id}")%></td>
               <% else %>
                  <td></td>
               <% end %>
               <% if l.facebook_link %>
                  <td><%= link_to('facebook', l.facebook_link)%></td>
               <% else %>
                  <td></td>
               <% end %>
               <td><%= link_to('email', "mailto:#{l.oc_email}") %></td>
               <td><%= l.oc_email %></td>
               <td><%= link_to('contactform', l.contact_form) %></td>
            </tr>
         <% end %>
      </table>
   </div>
<% end %>

<div style='clear: both;'>Share this petition on twitter! <%= link_to('tweet', "https://twitter.com/share", class: 'twitter-share-button' ) %></div>

app/views/welcome/index.html.erb
<script type="text/javascript" async src="//platform.twitter.com/widgets.js"></script>

<% content_for :title do %>
   <%= "Tweetstorm Your Representatives #{@zip}" %>
<% end %>

<%= form_tag(welcome_index_path, method: :get, class: 'navbar-form', id: 'search-form') do %>
   <%= label_tag(:search_by_zip) %>
   <%= text_field(:search, :zip) %>
<% end %>

<% if @legislators %>
   <div class='basic_info'>
      <table>
         <tr>
            <th>Chamber</th>
            <th>Name</th>
            <th>Phone</th>
            <th>Skype</th>
            <th>Tweet</th>
            <th>Email</th>
            <th>Raw email</th>
            <th>Contact Form</th>
         </tr>

         <% @legislators.each do |l| %>
            <tr>
               <td><%= "#{l['chamber']}" %></td>
               <td><%= "#{l['first_name']} #{l['last_name']}" %></td>
               <td><%= link_to("#{l['phone']}", "tel:#{l['phone']}") %></td>
               <td><%= link_to('skype their phone number', l['skype_link']) %></td>
               <% if l['twitter_id'] %>
                  <td><%= link_to('tweet your support', "http://twitter.com/intent/tweet?text=I support Karls Law @#{l['twitter_id']}")%></td>
               <% else %>
                  <td></td>
               <% end %>
               <td><%= link_to('email', "mailto:#{l['oc_email']}") %></td>
               <td><%= l['oc_email'] %></td>
               <td><%= link_to('contactform', l['contact_form']) %></td>
            </tr>
         <% end %>
      </table>
   </div>
<% end %>
<div style='clear: both;'>Share us on twitter! <%= link_to('tweet', "https://twitter.com/share", class: 'twitter-share-button' ) %></div>